name: Version and Changelog

on:
  push:
    branches:
      - release
      - release-test

jobs:
  Test:
    uses: Helmholtz-AI-Energy/perun/.github/workflows/run_tests.yaml@cx/continous-release-refactor
  VersionAndChangelog:
    needs: Test
    concurrency: publish
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      newVersion: ${{ steps.semanticRelease.outputs.newVersion }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --with dev
    - name: Update version and changelog
      id: semanticRelease
      run: |
        poetry run semantic-release version --no-vcs-release --skip-build
        NEW_VERSION="$(git describe)"
        echo $NEW_VERSION
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
